{"uuid": "148dec28-b5a8-4318-94a2-a42f49897ead", "children": ["a1469b0a-39d7-4fa0-988d-cafb86b3caec", "478ad1c0-7fb6-4f84-8151-5a1c6f35a0eb"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"D:\\python_projects\\Automation_framework\\Tests\\framework_login_test.py\", line 13, in test_setup\n    driver = webdriver.Chrome(\"../drivers/chromedriver.exe\")\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1589108303879, "stop": 1589108303879}], "start": 1589108303879, "stop": 1589108304138}