{"uuid": "a75f1900-25da-42ce-9688-d8ca1a7e85c1", "children": ["c57e384f-557c-4df3-9085-83b3eb30df11", "8b60a769-ce52-4211-a4b4-8f514e4ca03d"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\python_projects\\automation_framework\\conftest.py\", line 12, in test_setup\n    driver = webdriver.Chrome(\"../drivers/chromedriver.exe\")\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1589108303501, "stop": 1589108303501}], "start": 1589108303501, "stop": 1589108303875}