{"uuid": "3730f3a6-34d9-4eaa-8515-69759ca9f139", "children": ["ef827aa5-e122-4e6a-b830-42285b06e4bf", "223e5d9c-acde-4188-81e1-c18a4caaf2f1"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"D:\\python_projects\\Automation_framework\\Tests\\login_test.py\", line 10, in test_setup\n    driver = webdriver.Chrome(\"../drivers/chromedriver.exe\")\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Vaidehi Deshpande\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1589108304009, "stop": 1589108304010}], "start": 1589108304009, "stop": 1589108304137}